#ifndef PSDDL_PDS2PSANA_ARCHON_DDL_H
#define PSDDL_PDS2PSANA_ARCHON_DDL_H 1

// *** Do not edit this file, it is auto-generated ***

#include <vector>
#include <boost/shared_ptr.hpp>
#include "psddl_psana/archon.ddl.h"
#include "pdsdata/psddl/archon.ddl.h"
namespace psddl_pds2psana {
} // namespace psddl_pds2psana
#endif // PSDDL_PDS2PSANA_ARCHON_DDL_H
